name: regional-rail-equity
channels:
  - conda-forge
dependencies:
  - python=3.9*
  - pyproj<3
  - geopandas<0.9
  - psycopg2
  - geoalchemy2
  - xlrd
  - xlsxwriter
  - openpyxl
  - jupyterlab
  - python-dotenv
  - black
  - flake8
  - tqdm
  - mkdocs-material
  - mkdocstrings
  - markdown-include
  - pytest
  - pip
  - pip:
      - pg-data-etl
      - --editable .
