name: regional-rail-equity
channels:
  - conda-forge
dependencies:
  - python=3.9*
  - pyproj
  - geopandas
  - psycopg2
  - geoalchemy2
  - xlrd
  - xlsxwriter
  - openpyxl
  - python-dotenv
  - black
  - flake8
  - pytest
  - rich
  - pip
  - pip:
      - pg-data-etl
      - --editable .
