poverty = {
    "filepath": "EA_A113100 - Poverty status (4) (Households for which poverty status is determined)/C13.shp",
    "sql_tablename": "data.ctpp_poverty_by_household",
    "names": [
        "ctpp_id",
        "label",
        "name",
        "geoid",
        "est_total_poverty_status",
        "moe_total_poverty_status",
        "est_below_100pct_poverty_status",
        "moe_below_100pct_poverty_status",
        "est_100_to_149pct_poverty_status",
        "moe_100_to_149pct_poverty_status",
        "est_at_or_above_150pct_poverty_status",
        "moe_at_or_above_150pct_poverty_status",
        "geometry",
    ],
}

race = {
    "filepath": "EA_A101108 - Race (5) (All persons)/C13.shp",
    "sql_tablename": "data.ctpp_race_all_people",
    "names": [
        "ctpp_id",
        "label",
        "name",
        "geoid",
        "est_all_races",
        "moe_all_races",
        "est_white_alone",
        "moe_white_alone",
        "est_black_alone",
        "moe_black_alone",
        "est_asian_alone",
        "moe_asian_alone",
        "est_other",
        "moe_other",
        "geometry",
    ],
}

english = {
    "filepath": "EA_A117200 - Ability to speak English (3) by Language spoken at home (13) (Persons 5 years old and over in households)/C13.shp",
    "sql_tablename": "data.ctpp_language_at_home",
    "names": [
        "ctpp_id",
        "label",
        "name",
        "geoid",
        "est_total",
        "moe_total",
        "est_english",
        "moe_english",
        "est_spanish",
        "moe_spanish",
        "est_french_hatian_cajun",
        "moe_french_hatian_cajun",
        "est_germanic",
        "moe_germanic",
        "est_russian_slavic",
        "moe_russian_slavic",
        "est_indo_european",
        "moe_indo_european",
        "est_korean",
        "moe_korean",
        "est_chinese",
        "moe_chinese",
        "est_vietnamese",
        "moe_vietnamese",
        "est_tagalog",
        "moe_tagalog",
        "est_other_aapi",
        "moe_other_aapi",
        "est_arabic",
        "moe_arabic",
        "est_other",
        "moe_other",
        "geometry",
    ],
}

mode_of_travel = {
    "filepath": "EA_B102201 - Minority Status (3) by Means of Transportation (11) (Workers 16 years and over)/C13.shp",
    "sql_tablename": "data.ctpp_travel_mode",
    "names": [
        "ctpp_id",
        "label",
        "name",
        "geoid",
        "est_total",
        "moe_total",
        "est_drove_alone",
        "moe_drove_alone",
        "est_drove_cp2",
        "moe_drove_cp2",
        "est_drove_cp3plus",
        "moe_drove_cp3plus",
        "est_bus_trolleybus",
        "moe_bus_trolleybus",
        "est_streetcar_trolleybus_subway_elevated",
        "moe_streetcar_trolleybus_subway_elevated",
        "est_railroad_ferryboat",
        "moe_railroad_ferryboat",
        "est_bike",
        "moe_bike",
        "est_walk",
        "moe_walk",
        "est_taxi_motorbike_other",
        "moe_taxi_motorbike_other",
        "est_wfh",
        "moe_wfh",
        "geometry",
    ],
}

ctpp_configurations = [poverty, race, english, mode_of_travel]
